name: Deploying Hop Digital Website âš™ï¸

on:
  push:
    branches:
      - main

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue ğŸ‘·
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: build-vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'HOPDigital'
          reponame: 'hop-webiste'
          token: ${{ secrets.GITHUB_TOKEN }}